let computerTerms = [
  {word: 'keyboard', hint: 'A tool with letters and numbers used to type on a computer.'},
  {word: 'monitor', hint: 'The screen where you see everything on your computer.'},
  {word: 'processor', hint: 'The brain of the computer that processes data and runs programs.'},
  {word: 'RAM', hint: 'Temporary memory that helps your computer run multiple programs at once.'},
  {word: 'storage', hint: 'A place where your files and data are saved on the computer.'},
  {word: 'router', hint: 'A device that connects your computer to the internet.'},
  {word: 'USB', hint: 'A small, portable device used to transfer data between computers.'},
  {word: 'browser', hint: 'A program that lets you visit websites on the internet.'},
  {word: 'email', hint: 'A way to send messages and files over the internet.'},
  {word: 'cloud', hint: 'A place to store and access files over the internet, not on your computer.'},
  {word: 'software', hint: 'Programs or applications that run on a computer.'},
  {word: 'hardware', hint: 'The physical parts of a computer like the keyboard, monitor, and mouse.'},
  {word: 'network', hint: 'A group of connected computers that can share information.'},
  {word: 'firewall', hint: 'A security system that protects your computer from threats on the internet.'},
  {word: 'file', hint: 'A digital document that stores information, like a text or picture.'},
  {word: 'folder', hint: 'A virtual container where you organize and store files.'},
  {word: 'shortcut', hint: 'An icon on your desktop that quickly opens a program or file.'},
  {word: 'virus', hint: 'A harmful program that can infect your computer and cause damage.'},
  {word: 'wifi', hint: 'A wireless way to connect to the internet without using cables.'},
  {word: 'cache', hint: 'A temporary storage area that helps websites and apps load faster.'},
  {word: 'pixel', hint: 'A tiny dot of color that makes up the images on your screen.'},
  {word: 'codec', hint: 'A tool used to compress and decompress audio and video files.'},
  {word: 'kernel', hint: 'The core part of a computer’s operating system that manages hardware.'},
  {word: 'domain', hint: 'The address of a website, like google.com.'},
  {word: 'cookie', hint: 'Small data stored by websites to remember your preferences.'},
  {word: 'clipboard', hint: 'A temporary space where things you copy or cut are stored.'},
  {word: 'ping', hint: 'A signal sent to test the speed of a connection between two devices.'},
  {word: 'backup', hint: 'A copy of your data stored in case of loss or damage.'},
  {word: 'malware', hint: 'Malicious software designed to harm your computer or steal data.'},
  {word: 'bitmap', hint: 'An image made up of individual pixels, often larger in file size.'}
];